
name:superlinter

on push

jobs:
   super-lint:
   name:lintcodebase
   runs-on ubuntu latest

   steps:
       -name:checkout code 
       uses:actions/checkout@v2
       env:
         DEFAULT_BRANCH:main
         GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}

